name: backend
on:
  push:
    paths-ignore:
      - '**/*.md'

defaults:
  run:
    working-directory: ./backend

jobs:
  TestAndBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm ci
      - run: npm run code:check
      - run: npm run test:cov
      - run: npm run build
      - name: Coveralls
        uses: coverallsapp/github-action@master
        # if: github.ref == 'refs/heads/master'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
